apiVersion: v1
kind: Secret
metadata:
  name: crm-api-secrets
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: postgres
  DB_URL: jdbc:postgresql://crm-db:5432/crm
  DB_USER: postgres
  KAFKA_BOOTSTRAP: crm-events:9092
  JWT_ISSUER_URI: http://idp:8080/oauth2
